### ISSUE TITLE
Big Refactor Passing Message and it's Meta Data into all things so Functions have state like "too", "filter", "date_range" and more

### ISSUE THREAD

**Issue by alnutile** [LlmLaraHub/larallama#35]
Message becomes more the State holder of the request and using it's meta_data field and dto we can store more history like date_range, tool, filter etc

- [ ]  Chat Controller
- [ ] Orchestrate
- [ ] Functions should all just need Message and not Message array 
- [ ] Anonymous Chat like API should have a Chat history and become part of this
- [ ] Then come back to Date Range and Distance Query to show how all of this can work
- [ ] Then in the UI show the "State" of the message so we can "Rerun" it more easily
